import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Paytone_One, Space_Grotesk } from "next/font/google";

import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";

const inter_init = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const paytone = Paytone_One({
    variable: "--font-paytone-one",
    weight: "400",
    subsets: ["latin"],
});

const sparkGrotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${sparkGrotesk.variable} ${paytone.variable} ${inter_init.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <LayoutWrapper>{children}</LayoutWrapper>
            </body>
        </html>
    );
}
